### ISSUE TITLE
Problem: missing cronos NFT  minting

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/defi-wallet-core-rs#458]
add cronos NFT mint, issue apis
erc20, erc721 , erc1155

this will be used for NFT generation tool

**Comment by damoncro** [comment]
It could be done by loading abi directly.

**Comment by tomtau** [comment]
there's no standardized "mint/issue API", given every contract can be different... and generally this is done one-off in dedicated tools instead of being done dynamically by a wallet.
unless this is meant to use testnet faucet / external service or some fixed contract templates (e.g. just have a binding for `_safeMint` https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.6.0/contracts/token/ERC721/ERC721.sol#L248), I'm not sure what this is meant to do?

**Comment by damoncro** [comment]
One use case is that we provide a fixed contract template for users to mint nft easily?

**Comment by damoncro** [comment]
Yay, the NFT faucet possibly.

**Comment by tomtau** [comment]
> One use case is that we provide a fixed contract template for users to mint nft easily?

still -- is that something to be in the wallet? it looks like that's something in docs / other developer tools ?

**Comment by damoncro** [comment]
yes... keep this ticket on hold first..

**Comment by tomtau** [comment]
also good to discuss with Terence on Slack who was talking about it in the mobile context... I'm assuming it'd be via a dedicated external service API, so good to check whether the could be leveraged here?

**Comment by leejw51crypto** [comment]
how about adding general compiled solidity code deploy?

**Comment by tomtau** [comment]
the compiled code would have static values for parts that one will want to override (token URI function, denomination, balances...)

**Comment by leejw51crypto** [comment]
i see, how about providing compiling on the fly from solidity?

**Comment by tomtau** [comment]
embedding a solidity compiler, especially if it's unknown whether this feature is needed in end-user wallets (given minting is generally done once by developers in dedicated tools, not by end user wallets), seems quite an overkill?
